selftests: vDSO: Add KHDR_INCLUDES to CFLAGS for vdso_test_{chacha,vgetrandom}
I'm not sure if this is correct, but without KHDR_INCLUDES I get errors
like:

In file included from /home/xry111/git-repos/linux/include/linux/limits.h:7,
                 from /usr/include/bits/local_lim.h:38,
                 from /usr/include/bits/posix1_lim.h:161,
                 from /usr/include/limits.h:195,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14.2.0/include/limits.h:210,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14.2.0/include/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14.2.0/include/limits.h:34,
                 from /home/xry111/libsodium/include/sodium/export.h:7,
                 from /home/xry111/libsodium/include/sodium/crypto_stream_chacha20.h:14,
                 from vdso_test_chacha.c:6:
/usr/include/bits/xopen_lim.h:99:6: Error: missing binary operator before token "("
   99 | # if INT_MAX == 32767
      |      ^~~~~~~

The problem is the kernel include/linux/limits.h is not a UAPI header
and it's not intended to be included by a libc header.  Add
$(KHDR_INCLUDES) so the UAPI linux/limits.h will be pick up.

Signed-off-by: Xi Ruoyao <xry111@xry111.site>